version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - aws codebuild batch-get-builds --ids $CODEBUILD_BUILD_ID --query 'builds[].sourceVersion' --output text
      - echo CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
      - echo env
      - env
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
